/*
============================================
CREATE DATABASE AND SCHEMAS FOR MEDALLION
============================================
WARNING : CHECKS FOR EXISTING DB AND DROPS, DELETES EXISTING DATA IF ANY
*/

--USE MAIN MASTER DB
USE master;
GO

--CHECK IF DB EXISTS AND DROP
IF EXISTS (SELECT 1 FROM sys.databases WHERE name='FirstDWHProject')
BEGIN
	ALTER DATABASE FirstDWHProject SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE FirstDWHProject;
END
GO

--CREATE FRESH DB
CREATE DATABASE FirstDWHProject;
GO

--USE CREATED DB
USE FirstDWHProject;
GO

--CREATE LAYERS/SCHEMA
CREATE SCHEMA bronze;
GO
CREATE SCHEMA silver;
GO
CREATE SCHEMA gold;
GO

